### ISSUE TITLE
Query non text fields

### ISSUE THREAD

**Issue by matteogrolla** [flaxsearch/luwak#104]
It's not clear to me how to query non text fields, ex an int field.
Could you make an example or a test about it?

**Comment by romseygeek** [comment]
Hi, the default lucene query parser doesn't handle numeric fields, unfortunately, mainly because lucene is schemaless and it's not possible to detect old-style numeric fields just from index data.

You can override QueryParser#newTermQuery() and QueryParser#newRangeQuery() to correctly deal with old-style numerics or new-style points, depending on your own schema information - the solr and elasticsearch query parsers do this, and they're a good place to look for examples.

**Comment by matteogrolla** [comment]
Thank you so much Alan

Il 07 nov 2016 10:42 AM, "Alan Woodward" <notifications@github.com> ha
scritto:
