### ISSUE TITLE
Highlighting some queries but not others

### ISSUE THREAD

**Issue by dyshi** [flaxsearch/luwak#59]
Hello,

I noticed that as of commit b69d0293d6ea81deb551813248f59e9b13b3acbb
support for specifying whether to highlight a query or on a per query basis has been removed with the introduction of the HighlightingMatcher.

My question is what is the best way to maintain the ability to highlight on a per query basis?

Thanks!

**Comment by dcollins53** [comment]
@romseygeek, this is in relation to our trying to upgrade to latest Luwak master (release 1.2.1), we had a Matcher which explicitly decided whether to delegate to SimpleMatcher or what was IntervalsMatcher (and is now HighlightingMatcher), so we avoided unnecessary calls to intervals.

Are we saying that optimization is no longer necessary?

I wasn't sure if we could use the Metadata in the query, but I think that is only passed to the Presearcher not to the Matcher?

**Comment by romseygeek** [comment]
Yes, at the moment the metadata is only passed to the Presearcher.  It wouldn't be too complicated to read it from docvalues and pass to the Matcher as well, though.  At the moment the whole MonitorQuery is serialized to a BinaryDocValues field, but we could split that up so that you don't need to deserialize the whole thing, or maybe re-jig it so that the metadata is serialized first.

**Comment by dyshi** [comment]
Can we get the metadata passed down to the matchers and have them decide what to do with it?

**Comment by dcollins53** [comment]
@romseygeek, ok, we'll have a go at that change, we'll start with the API update to CandidateMatcher, and see where that leads us...  Should be able to get a PR together in a day or so.

**Comment by dyshi** [comment]
I've submitted the PR here: https://github.com/flaxsearch/luwak/pull/60
thanks!

**Comment by romseygeek** [comment]
Merged in, thanks!
